'use client';
import{useEffect,useState}from'react';import Link from'next/link';import Navbar from'./Navbar';import Footer from'./Footer';import Card from'./Card';import{imageOf,titleOf,descriptionOf,getEnrichment}from'../lib/api';import{getCollection,setCollection}from'../lib/storage';
function save(item,type){const old=getCollection();const entry={id:item.id,type,title:titleOf(item),image:imageOf(item),savedAt:Date.now()};const exists=old.some(x=>x.id===entry.id&&x.type===entry.type);setCollection(exists?old.filter(x=>!(x.id===entry.id&&x.type===entry.type)):[entry,...old]);return !exists}
export default function DetailPage({type,id}){const[item,setItem]=useState(null),[related,setRelated]=useState([]),[extra,setExtra]=useState({}),[chapters,setChapters]=useState([]),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 useEffect(()=>{let dead=false;(async()=>{try{const r=await fetch(`/api/item?type=${type}&id=${encodeURIComponent(id)}`);const j=await r.json();if(!r.ok||!j.data)throw 0;if(dead)return;setItem(j.data);const title=titleOf(j.data);if(type==='manga'){const ch=await fetch(`/api/chapters?id=${encodeURIComponent(j.data.id)}`).then(x=>x.json()).catch(()=>({data:[]}));if(!dead)setChapters(ch.data||[])} const jobs=[type==='anime'?fetch(`/api/related?q=${encodeURIComponent(title)}`).then(x=>x.json()).catch(()=>({data:[]})):Promise.resolve({data:[]}),type==='anime'?getEnrichment(title,'anime'):Promise.resolve({})];const[a,e]=await Promise.all(jobs);if(!dead){setRelated(a.data||[]);setExtra(e||{});const c=getCollection();setSaved(c.some(x=>x.id===j.data.id&&x.type===type))}}catch{if(!dead)setError('This title could not be opened.')} })();return()=>{dead=true}},[type,id]);
 if(error)return <div className="site"><Navbar/><main className="error-page"><span className="eyebrow">404 / DOSSIER</span><h1>Couldn’t open this title.</h1><div className="back-actions"><Link className="btn-primary" href="/">← Back home</Link><button className="btn-ghost" onClick={()=>history.back()}>Go back</button></div></main><Footer/></div>;
 const a=item?.attributes;if(!item)return <div className="site"><Navbar/><main className="detail-loading"><div className="loading-ring"/></main><Footer/></div>;
 const toggle=()=>setSaved(save(item,type));
 return <div className="site"><Navbar/><main><section className="detail-hero"><div className="detail-bg" style={{backgroundImage:`url(${imageOf(item)})`}}/><div className="detail-poster"><img src={imageOf(item)} alt={titleOf(item)}/></div><div className="detail-copy"><div className="back-row"><button onClick={()=>history.back()}>← Go back</button><Link href="/">⌂ Home</Link></div><span className="eyebrow">{type==='anime'?'ANIME DOSSIER':'MANGA / MANHWA DOSSIER'}</span><h1>{titleOf(item)}</h1><div className="facts"><span>{a?.status||'Unknown status'}</span><span>{a?.startDate||a?.year||'—'}</span><span>{type==='anime'?`${a?.episodeCount||extra.episodes||'?'} episodes`:`${a?.chapterCount||'?'} chapters`}</span>{a?.averageRating&&<span>{Math.round(Number(a.averageRating))}% rating</span>}</div><p>{descriptionOf(item)||'No synopsis is available for this title yet.'}</p><div className="hero-actions"><button className="btn-primary" onClick={toggle}>{saved?'✓ In collection':'＋ Add to collection'}</button>{extra.trailer&&<a className="btn-ghost" href={extra.trailer} target="_blank" rel="noreferrer">▶ Watch trailer</a>}{extra.malUrl&&<a className="btn-ghost" href={extra.malUrl} target="_blank" rel="noreferrer">More details ↗</a>}</div></div></section>
 <section className="detail-data"><div><span className="eyebrow">MATERIALS</span><h2>Everything<br/><i>in one place.</i></h2></div><div className="data-grid">{[['Rating',a?.averageRating?`${Math.round(Number(a.averageRating))}%`:'—'],['Popularity',a?.popularityRank?`#${a.popularityRank}`:'—'],['Episodes / Chapters',type==='anime'?(a?.episodeCount||extra.episodes||'—'):(a?.chapterCount||'—')],['Duration',a?.episodeLength?`${a.episodeLength} min`:'—'],['Genres',a?.genres?.join?.(', ')||extra.genres?.join?.(', ')||'Explore tags'],['Age rating',a?.ageRating||'—']].map(([k,v])=><div className="data-cell" key={k}><small>{k}</small><strong>{v}</strong></div>)}</div></section>
 {type==='manga'&&chapters.length>0&&<section className="chapters-section"><div className="row-head"><div><span className="eyebrow">MANGADEX / AVAILABLE CHAPTERS</span><h2>Read the latest chapters.</h2></div><span className="live">{chapters.length} LOADED</span></div><div className="chapter-list">{chapters.map(ch=><a key={ch.id} href={`https://mangadex.org/chapter/${ch.id}`} target="_blank" rel="noreferrer"><span>Chapter {ch.attributes?.chapter||'—'}{ch.attributes?.title?` — ${ch.attributes.title}`:''}</span><b>Read ↗</b></a>)}</div></section>}{type==='anime'&&extra.pictures?.length>0&&<section className="media-section"><div className="row-head"><div><span className="eyebrow">VISUAL ARCHIVE</span><h2>Screenshots & scenes</h2></div></div><div className="screenshots">{extra.pictures.map((src,i)=><img key={src+i} src={src} alt={`${titleOf(item)} scene ${i+1}`} loading="lazy"/>)}</div></section>}
 {type==='anime'&&extra.trailer&&<section className="trailer-section"><div><span className="eyebrow">TRAILER</span><h2>See it in motion.</h2></div><div className="trailer-frame"><iframe src={extra.trailer} title={`${titleOf(item)} trailer`} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/></div></section>}
 {related.length>0&&<section className="row-section related"><div className="row-head"><div><span className="eyebrow">COMPANION READING</span><h2>Manga you may want next</h2></div></div><div className="cards">{related.slice(0,6).map((x,i)=><Card key={x.id} item={x} type="manga" index={i}/>)}</div></section>}</main><Footer/></div>}