'use client';import{useEffect,useState}from'react';import{motion}from'motion/react';import Navbar from'./Navbar';import Footer from'./Footer';import Card from'./Card';import Search from'./Search';import{getCatalog,sections,titleOf,imageOf,descriptionOf}from'../lib/api';
function Row({title,section,items}){return <section className="row-section" id={section==='trending'?'anime':undefined}><div className="row-head"><div><span className="eyebrow">CURATED SIGNAL</span><h2>{title}</h2></div><span className="live">{items.length} TITLES</span></div><div className="cards">{items.map((x,i)=><Card key={x.id} item={x} index={i}/>)}</div></section>}
export default function Home(){const[data,setData]=useState({}),[hero,setHero]=useState(null),[loading,setLoading]=useState(true),[tab,setTab]=useState('trending'),[manga,setManga]=useState([]),[error,setError]=useState('');
 useEffect(()=>{let dead=false;(async()=>{try{const names=['trending','popular','latest','airing','upcoming','top'];const out=await Promise.allSettled(names.map(n=>getCatalog(n)));if(dead)return;const map={};names.forEach((n,i)=>{if(out[i].status==='fulfilled')map[n]=out[i].value.data||[]});setData(map);setHero(map.trending?.[0]||map.popular?.[0]);const mj=await getCatalog('trending','manga');if(!dead)setManga(mj.data||[])}catch{if(!dead)setError('Some catalogues are temporarily unavailable.')}finally{if(!dead)setLoading(false)}})();return()=>{dead=true}},[]);
 const change=async s=>{setTab(s);if(data[s])return;try{const j=await getCatalog(s);setData(d=>({...d,[s]:j.data||[]}))}catch{setError('Could not load this signal.')}};
 return <div className="site"><Navbar/><main><section className="hero" id="discover"><div className="hero-grid"/><div className="orb orb-a"/><div className="orb orb-b"/><div className="hero-content"><motion.div initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.7}}><span className="eyebrow">THE ENTERTAINMENT INDEX / 001</span><h1>Find stories<br/><em>worth losing</em><br/>time to.</h1><p>Auravue turns anime, manga and manhwa into one cinematic discovery universe—with trailers, visual archives and a personal collection.</p><div className="hero-actions"><a className="btn-primary" href="#search">Explore universe <span>↗</span></a><a className="btn-ghost" href="#anime">Browse titles</a></div></motion.div></div>{hero&&<motion.div className="hero-card" initial={{opacity:0,x:40,rotate:4}} animate={{opacity:1,x:0,rotate:0}} transition={{duration:.9,delay:.2}}><img src={imageOf(hero)} alt={titleOf(hero)}/><div className="hero-card-overlay"/><div className="hero-card-meta"><span>FEATURED NOW</span><strong>{titleOf(hero)}</strong><small>{descriptionOf(hero).slice(0,120)}{descriptionOf(hero).length>120?'…':''}</small><a href={`/anime/${hero.id}`}>Open dossier ↗</a></div></motion.div>}<div className="hero-scroll">SCROLL TO EXPLORE <span>↓</span></div></section>
<Search/><section className="signal" id="genres"><div><span className="eyebrow">DISCOVERY MODES</span><h2>Choose a mood.<br/><i>Let the catalogue answer.</i></h2><p className="signal-note">Fast filters are intentionally lightweight; use search for an exact title and the catalogue signals below for discovery.</p></div><div className="mood-grid">{['Action','Romance','Fantasy','Mystery','Psychological','Adventure','Comedy','Sci‑Fi'].map((x,i)=><a href="#anime" key={x} onClick={()=>change('popular')}><span>{String(i+1).padStart(2,'0')}</span>{x}<b>↗</b></a>)}</div></section>
<section className="catalog-tabs"><div className="tab-title"><span className="eyebrow">ANIME INDEX</span><h2>Explore by signal</h2></div><div className="tabs">{sections.map(s=><button key={s.key} className={tab===s.key?'active':''} onClick={()=>change(s.key)}>{s.label}</button>)}</div></section>
{error&&<div className="notice">{error}</div>}{loading?<div className="loading-grid">{Array.from({length:6}).map((_,i)=><div className="skeleton" key={i}/>)}</div>:<Row title={sections.find(x=>x.key===tab)?.label||'Trending'} section={tab} items={data[tab]||[]}/>}
<section className="row-section" id="manga"><div className="row-head"><div><span className="eyebrow">READING INDEX</span><h2>Manga & manhwa</h2></div><a className="live" href="/manga">OPEN READING HUB →</a></div><div className="cards">{manga.slice(0,6).map((x,i)=><Card key={x.id} item={x} type="manga" index={i}/>)}</div></section>
<section className="manifesto"><span className="eyebrow">AURAVUE / 2026</span><h2>Less noise.<br/><i>More discovery.</i></h2><p>Trailers. Screenshots. Dossiers. Saved collections. One polished interface for the worlds you keep coming back to.</p></section></main><Footer/></div>}